# Generated by Django 5.1.3 on 2024-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("status", models.CharField(default="available", max_length=50)),
                ("ipv4", models.CharField(max_length=50)),
                ("ipv6", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("spuCores", models.IntegerField()),
                ("ram", models.IntegerField()),
                ("ssd", models.IntegerField()),
                ("ip", models.GenericIPAddressField()),
                ("bandwidth", models.IntegerField()),
                ("operating_system", models.CharField(max_length=50)),
            ],
        ),
    ]
